### ISSUE TITLE
Support for lighting in the generated pdf

### ISSUE THREAD

**Issue by CsatiZoltan** [johnyf/fig2u3d#2]
Is there any way to export the lighting set in MATLAB to the pdf? I have Acrobat Pro and it has an option to import light from file. A javascript file which does it would be great since Adobe lights do not work for surface plots.

**Comment by johnyf** [comment]
I am not sure what the lightning set includes, but a good place to look at is the document that defines the IDTF format (should be somewhere in [there](https://sourceforge.net/projects/u3d/files/Universal%203D%20Sample%20Software/Gold%20Update%201.2/) and linked from the `fig2u3d` manual). Regarding the code, camera settings are exported by [calling](https://github.com/johnyf/fig2u3d/blob/74fe75d424665e3a8194337036f923962620bfd5/fig2u3d.m#L242) the function [`vew2vws`](https://github.com/johnyf/fig2u3d/blob/74fe75d424665e3a8194337036f923962620bfd5/view2vws.m) and shading/materials/colors are defined around [here](https://github.com/johnyf/fig2u3d/blob/74fe75d424665e3a8194337036f923962620bfd5/fig2idtf/output/mesh_diffuse_colors.m) (including neighboring files).
