### ISSUE TITLE
matplotlib plots?

### ISSUE THREAD

**Issue by MengGuo** [johnyf/fig2u3d#7]
Awesome project, Ioannis. 

Wondering have you thought about the difficulties of doing similar things for matplotlib figures?

**Comment by johnyf** [comment]
Thank you, Meng. Based on https://github.com/matplotlib/matplotlib/issues/2672 and the later comments at http://stackoverflow.com/a/35511373/1959808, exporting 3 dimensional information from `matplotlib` seems to require major changes to `matplotlib` itself.

[`mayavi`](https://github.com/enthought/mayavi) seems a better candidate for implementing such exporting functionality, based on this discussion https://sourceforge.net/p/meshlab/discussion/499532/thread/147b4eb5/.
